# deployment
host: 0.0.0.0
port: 4000

site:
  url: https://jdip.github.io/Constance-City/

collections:
  burrows:
  towns:
  neighborhoods:
  buildings:
  outlets:
  corporations:
  gangs:
  crews:

